

version: '3.8'

services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    restart: always
    command:
      - pocketbase
      - serve
      - --http
      - 0.0.0.0:8090
      - --dir
      - /data
    networks:
      - app_network
    ports:
      - "8090:8090"
    volumes:
      - ./pocketbase:/data
  sveltekit:
    image: ghcr.io/viledub/playground:tag
    networks:
      - app_network
    environment:
      - POCKETBASE_URL=http://pocketbase:8090


networks:
  app_network:
    external: true
    name: ${NETWORK_NAME}
