

version: '3.8'

services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    restart: always
    networks:
      - app_network
    ports:
      - "8090:8090"
    volumes:
      - ./pocketbase:/pb_data
  sveltekit:
    image: ghcr.io/viledub/playground:tag
    networks:
      - app_network
    ports:
      - "7777:3000"
    environment:
      - POCKETBASE_URL=http://pocketbase:8090


networks:
  app_network:
    external: true
    name: ${NETWORK_NAME}
